import json

# Dữ liệu đầu vào
data = [
"ăn cơm hay ăn",
"té đái",
"quả báo nhãn tiền",
"cạp đất ăn",
"hèn quá",
"ăn gì tôi cúng",
"ăn gì tui cúng",
"lấy ráy tai",
"hèn hạ",
"trơ trẽn",
"banh cái tai ra",
"bố láo",
"lỗ tai có bị",
"vô học",
"hỗn láo",
"đồ thất học",
"súc vật",
"điếc hả",
"bị câm",
"trâu bò",
"có não không",
"thần kinh hả",
"thần kinh có vấn đề",
"tâm thần",
"tán cho vỡ mồm",
"tát cho vỡ mồm",
"tát vỡ mồm",
"tán cho vỡ mặt",
"tát cho vỡ mặt",
"tát vỡ mặt",
"ỉa vào mồm",
"đồ thối tha",
"thứ giẻ rách",
"thứ bá dơ",
"con kia",
"lôi đầu ra",
"cặn bã xã hội",
"não ngắn",
"não không có nếp nhăn",
"tổ cha chúng bay",
"tổ cha chúng bây",
"con người hay con gì vậy",
"thất học",
"nghèo hèn",
"nói tiếng con bốn chân",
"loại bốn chân",
"ở dưới đất chui lên hả",
"thằng bắc kì",
"ngu dốt",
"mặt dày",
"thằng đàn bà",
"bất tài vô dụng",
"có lớn mà không có khôn",
"thối nát",
"thất đức",
"động cái não lên",
"cái mỏ hỗn",
"không có nhân cách",
"đầu đất",
"đàn ông mặc váy",
"già đầu",
"não úng",
"ngu như heo",
"lì như trâu",
"lì như bò",
"lì lợm",
"nói chuyện dơ",
"lú lẩn",
"lú lẫn",
"tứ chi",
"suy nghĩ bị dị tật",
"suy nghĩ dị tật",
"thiểu năng",
"nghiệp vô mồm",
"võ mồm",
"cái dân lừa đảo",
"thằng thiểu năng",
"ông già mày",
"ăn gì mà lì",
"mắc dại",
"mất dạy",
"đang sủa hả",
"không phát triển được trí não",
"não không phát triển",
"mắc dại quá",
"già cái đầu",
"không biết nhục",
"tính đàn bà",
"không ăn học",
"phát ngôn ra dơ",
"ăn cướp của người ta",
"ăn nói mất dạy",
"to cái mồm",
"bớt mõm lại",
"gọi cho chị sủa",
"sống chi cho chật đất",
"bố mẹ ông đi lừa đảo",
"láo cá",
"láu cá",
"ngu như gì",
"con hư tại mẹ",
"bám váy mẹ",
"cười vô mặt",
"làm trâu làm bò",
"mày",
"tao",
"mày sủa",
"ngồi đó sủa",
"đứng đó sủa",
"sủa lên",
"sủa gì",
"sủa à",
"ngu",
"con điên",
"thằng điên",
"mày điên",
"nó điên",
"em điên",
"bị điên",
"đồ điên",
"nói điên",
"khùng điên",
"điên khùng",
"điên hả",
"điên à",
"lì",
"con khùng",
"thằng khùng",
"mày khùng",
"nó khùng",
"em khùng",
"bị khùng",
"đồ khùng",
"nói khùng",
"khùng hả",
"khùng à",
"nhục",
"anh vẫn còn sống mà",
"bị điếc",
"biết đọc không",
"biết suy nghĩ không",
"bố đời",
"cái mặt mày",
"cái quần",
"cái trò mèo",
"cất cái mặt đi",
"có đi học không",
"phải người không",
"phải con người",
"con người hay con gì",
"con ranh",
"đầu óc có vấn đề",
"đầy đủ tay chân",
"để đức lại",
"làm xấu mặt",
"dơ bẩn",
"dở hơi",
"đội quần",
"đúng chất lừa đảo",
"đừng có báo đời",
"giả điên",
"già mồm",
"gian xảo",
"hèn chi không có con",
"hiểu tiếng việt",
"học lại",
"hùa nhau dựt",
"hùa nhau giật",
"không có học",
"không có não",
"không có ra gì",
"lì quá vậy",
"lớn cái đầu",
"lì vậy",
"mất nết",
"mày bảo",
"mày nói cái gì",
"mở tai ra",
"nết khó ưa",
"nghiệp mình để lại",
"ngu thế",
"người bắc kì",
"như rẻ rách",
"như giẻ rách",
"nói tiếng con",
"rác rưởi",
"mỏ thúi",
"mỏ thối",
"miệng thúi",
"miệng thối",
"mồm thúi",
"mồm thối",
"sống chui sống nhủi",
"tao nói cho mày nghe",
"thiếu giáo dục",
"thứ đàn ông",
"vô dụng",
"vớ vẩn",
"vô văn hóa",
"cái bản mặt",
"dân bắc kì",
"đéo đáng mặt",
"hư một thế hệ",
"kệ mày",
"không có ăn học",
"không có văn hóa",
"láo toét",
"mất khả năng giao tiếp",
"năn nỉ quỳ lạy",
"nhét vào mồm",
"quá lì",
"xin tiền nhà mày",
"lấy cái quần",
"hôi sữa",
"ngoắc cái mồm",
"bê đê",
"đồ hèn",
"già hai thứ tóc",
"ngu như bò",
"thần kinh",
"đầu hai thứ tóc",
"óc trâu",
"mở cái não ra",
"hèn nhát",
"ngu ngục",
"bần tiện",
"nói tiếng người",
"khỏi ngốc đầu lên",
"khỏi ngóc đầu lên",
"nghèo mạt kiếp",
"hạ lưu",
"cái đạo đức ở đâu",
"ăn bậy chứ đừng nói bậy",
"không biết dạy con",
"có mấy đồng bạc lẻ",
"đê tiện",
"mày nói chuyện với ai",
"cúng ba đời ",
"hèn vừa thôi",
"kém thông minh",
"đồ dân tộc",
"cà chớn",
"đú đỡn",
"ẳng lên",
"ngớ ngẩn",
"báo đời",
"ăn hại",
"sống tệ",
"cô hồn",
"rẻ mạt",
"hiểu tiếng người",
"con đàn bà",
"mặc váy",
"lú não",
"lú vậy",
"lú rồi",
"bị lú",
"bất lịch sự",
"sủa tiếp",
"lỗ tai bị",
"đâu phải con nít",
"biến dùm",
"biến giùm",
"biếng nhác",
"ngu như chó",
"thằng đàn ông",
"như chó",
"đú đởn",
"thằng nhà quê",
"có ăn học không",
"có ăn có học không",
"là con gì",
"loại người như",
"lắp não",
"gắn não",
"chết cả nhà",
"đừng có ra đường",
"cẩn thận đi tù",
"chặt đầu",
"cán banh xát",
"còng đầu",
"tao chém",
"lôi cái đầu",
"chém chết cha",
"đi tù mọc gong",
"đập tiệm",
"chém chết mẹ",
"san bằng",
"đốt nhà",
"truy nã",
"đi tù mục xương",
"cẩn thận cái mạng",
"cẩn thận tứ chi",
"trông con cho kĩ vào",
"ra đường cẩn thận",
"ra đường xe cán",
"ra đường sét đánh",
"ra đường coi chừng",
"chặt tay",
"chặt chân",
"đăng lên mạng xã hội",
"dán hình lên cột điện",
"tù mọt gông",
"tay nào cầm tiền lấy tay đó",
"tế sống",
"gông cổ",
"chôn sống",
"tông xe",
"lôi cái đầu anh ra",
"lôi đầu ba mẹ anh ra trả",
"đập vô cái mặt anh",
"truy nã cả gia đình",
"cắt cổ",
"không đưa tiền thì đập vô mặt",
"truy nã tìm con bà",
"lôi đầu",
"lôi đầu cha đầu mẹ ra",
"nghiệp quật",
"câm cái mồm",
"giết người",
"giết chết",
"giết mày",
"giết nó",
"tao giết",
"bị giết",
"đòi giết",
"nó giết",
"chém người",
"chém lộn",
"chém nó",
"chém tao",
"chém ai",
"bị chém",
"đòi chém",
"đâm chém",
"nó chém",
"dọa chém",
"dán lệnh truy nã",
"cán banh xác",
"cẩn thận với tao",
"chém chết",
"chém giết",
"cho sập tiệm",
"coi chừng tao",
"cồng đầu",
"đấm bản mặt mày",
"đập hết",
"đập nát nhà",
"đốt bà",
"đứt gân máu",
"khởi tố truy nã",
"khởi tố truy nả",
"kiện tới cùng",
"liệu hồn",
"mày cứ đợi đấy",
"muốn ăn chửi",
"nát tiệm giờ",
"tao đá vào cái mặt mày",
"tao gặp mày",
"tội phạm",
"truy lùng",
"vô tù",
"xuống mồ đi",
"cào nhà",
"chém đi",
"coi chừng bản thân",
"chém hộ",
"bỏ tù",
"phát lệnh truy nã",
"nát máy",
"truy sát",
"dở nhà",
"quậy banh nhà",
"phát tờ rơi thông tin nợ",
"tôi không tha",
"chôn cái sim",
"cho anh đi tù",
"cho chị đi tù",
"xách đầu ra trả nợ",
"xé lịch",
"đếm lịch",
"đăng phây sờ bút",
"đăng phây sờ búc",
"đăng phay sờ bút",
"đăng phay sờ búc",
"đăng phây bút",
"đăng phây búc",
"đăng phay bút",
"đăng phay búc",
"đăng phết bút",
"đăng phết búc",
"đăng phết sờ bút",
"đăng phết sờ búc",
"Vành móng ngựa",
"dở cái nhà",
"bóc lịch",
"bốc lịch",
"mày làm gì được tao",
"dám chém không",
"mày đừng có hù tao",
"ra cầu nhảy xuống",
"mày liệu hồn",
"sủa nữa",
"sủa đi",
"mày nghe cho kĩ",
"bố nói thẳng",
"tao hù mày",
"làm gì được tao",
"giỏi lên đây này",
"xách dao lên đây",
"giỏi kéo đồng bọn lên đây",
"câm cái mõm",
"im cái mồm lại",
"vểnh cái tai",
"dảnh cái lỗ tai",
"biến mẹ đi",
"lên đây chém chết mẹ",
"san bằng nơi buôn bán",
"ra cầu nhảy xuống đi",
"đốt nhà đi",
"đi chết đi",
"bóp mũi chết đi",
"câm mõm",
"biến mẹ giùm",
"coi chừng tai nạn",
"thử lên đây",
"tao lại sợ mày quá",
"tao sợ mày",
"tao sợ",
"kéo người ra đây",
"sủa cho đã đi",
"nhảy cầu",
"câm họng",
"câm cái họng lại",
"câm hay sao",
"chơi kiểu gì",
"cơm tù",
"đánh răng chưa",
"đem dao đem búa",
"đừng ra đường",
"gọi cháy máy",
"gọi cho mẹ mày",
"gọi điện bố mày",
"gọi tiếp cho chừa",
"im cái miệng",
"in hình của",
"má mày",
"mặc váy đi",
"mày chửi ai",
"mày muốn địt ai",
"mày nghe chưa",
"mày thích chửi không",
"mày thích chửi nhau",
"muốn đi tù không",
"nhục nhã",
"ra lệnh cho tao",
"sáng giờ đánh răng chưa",
"tối nay tao đến",
"vác cái mặt",
"thích gọi thì làm gì",
"câm lại đi",
"câm mồm",
"đem dao ra",
"ngon lên đây",
"bớt sủa",
"câm",
"ói tiền ra",
"hộ bố cái",
"cứ gọi đấy",
"gọi tới khuya",
"chửi lớn lên",
"chửi to lên",
"chửi nhiều vô",
"chửi nữa đi",
"chửi tiếp",
"chửi nhanh lên",
"đụ đĩ",
"chó chết",
"địt con mẹ",
"đĩ ngựa",
"bú cu",
"cạp lồn",
"rảnh háng",
"hãm lồn",
"con chó",
"mẹ cái bọn",
"cạp lồn ăn",
"chó đẻ",
"đĩ mẹ mày",
"thằng cha",
"chửi con mẹ mày đó",
"địt mẹ",
"lồn mẹ mày",
"cút cái đĩ mẹ mày",
"câm mẹ cái mồm",
"cái lồn",
"con nít ranh",
"cha mày",
"đĩ mẹ",
"thằng lồn",
"con đĩ",
"quỷ cái",
"đồ dơ bẩn",
"chơi chó",
"đĩ lồn",
"lồn mẹ",
"thằng đĩ",
"chó cái",
"lồn má",
"con cặc",
"thằng chó",
"đĩ chó",
"đồ khốn",
"khốn nạn",
"đù má",
"đù mẹ",
"đồ chó đẻ",
"cái lồn mẹ mày",
"con đĩ ngựa",
"thằng chó đẻ",
"lồn má mày",
"đụ mẹ",
"thằng khốn nạn",
"thằng khốn",
"bố mày",
"mẹ mày",
"thằng cha mày",
"đĩ mẹ nó",
"vãi lồn",
"con mặt lồn",
"đầu bùi",
"quần què",
"thằng cha con gái mẹ",
"con mẹ nó",
"chết mẹ mày giờ",
"cái lồn má",
"đụ quen biết mới cho số",
"con mẹ mày",
"địt",
"đụ",
"đéo",
"lồn",
"bà nội mày",
"biến mẹ mày",
"chửi con mẹ mày",
"con gái mẹ",
"đầu buồi",
"đéo hiểu",
"đéo muốn nghe",
"đéo rảnh",
"đéo thích",
"đỉ mẹ mày",
"địt cái con mẹ",
"địt cụ",
"địt mẹ mày",
"đụ đỉ",
"đụ má",
"đụ mẹ mày",
"đụ rảnh háng",
"hãm lờ",
"làm quần què gì",
"lì như chó",
"mả bố mày",
"mả cha mày",
"mặt chó mày",
"mày chửi ai vậy",
"mày hãy nghe",
"mày lừa đảo",
"ông nội của anh",
"sống chó",
"thứ hãm",
"tiên sư bố",
"cái mả mẹ",
"mả cha",
"bố nhà mày",
"con lồn này",
"mã bố nhà mày",
"mả bố nhà mày",
"mày bị câm",
"con đỉ mẹ mày",
"con đỉ mẹ nó",
"cứt",
"cức"
]

# Các bucket
buckets = ["B1 BOM", "B2", "B3", "B4B6", "B7+", "B1-B6"]

# Tạo JSON array hai chiều
result = []

for bucket in buckets:
    bucket_data = {
        "bucket": bucket,
        "items": data
    }
    result.append(bucket_data)

# Chuyển đổi thành JSON
json_result = json.dumps(result, ensure_ascii=False, indent=2)

# In kết quả
print(json_result)
