import json

# Dữ liệu đầu vào
data = [
"bố nói thẳng",
"câm họng",
"câm cái họng lại",
"câm cái mõm",
"câm hay sao",
"càng chửi càng gọi",
"chơi kiểu gì",
"chửi cha chửi mẹ",
"chửi đi",
"chửi lại coi",
"chửi lại đi",
"chửi lí nhí",
"chửi lớn lên",
"chửi to lên",
"chửi nhiều vô",
"chửi nữa đi",
"chửi tiếp",
"chửi nhanh lên",
"con cháu coi thường",
"cứ chửi",
"cứ chưởi",
"dám chém không",
"dám chửi",
"dám không",
"dám không nghe máy",
"dám không trả",
"dảnh cái lỗ tai",
"đánh răng chưa",
"đem dao đem búa",
"đẹp mặt luôn",
"đừng ra đường",
"giữ mặt mũi",
"gọi cháy máy",
"gọi cho mẹ mày",
"gọi điện bố mày",
"gọi tiếp cho chừa",
"hỗn",
"im cái miệng",
"im cái mồm lại",
"im đi",
"im miệng",
"im mồm",
"in hình của",
"kêu mẹ anh dạy",
"không biết nhục",
"má mày",
"mặc váy đi",
"mày chửi ai",
"mày muốn địt ai",
"mày nghe chưa",
"mày thích chửi không",
"mày thích chửi nhau",
"muốn đi tù không",
"nhục nhã",
"ra cầu nhảy xuống",
"ra lệnh cho tao",
"sáng giờ đánh răng chưa",
"sao chửi ít vậy",
"sao chưởi ít vậy",
"sống làm gì",
"tao hù mày",
"thách không trả",
"thích la không",
"tối nay tao đến",
"vác cái mặt",
"thích gọi thì làm gì",
"câm lại đi",
"chửi hay quá",
"còn chửi còn gọi",
"gọi cho chửi",
"câm mồm",
"mày làm gì được tao",
"mày đừng có hù tao",
"mày liệu hồn",
"sủa nữa",
"sủa đi",
"làm gì được tao",
"giỏi lên đây này",
"xách dao lên đây",
"giỏi kéo đồng bọn lên đây",
"vểnh cái tai",
"biến mẹ đi",
"lên đây chém chết mẹ",
"san bằng nơi buôn bán",
"ra cầu nhảy xuống đi",
"đốt nhà đi",
"bóp mũi chết đi",
"câm mõm",
"biến mẹ giùm",
"coi chừng tai nạn",
"thử lên đây",
"tao lại sợ mày quá",
"tao sợ mày",
"tao sợ",
"kéo người ra đây",
"sủa cho đã đi",
"nhảy cầu",
"ngon lên đây",
"đi kiện",
"bớt sủa",
"câm",
"ói tiền ra",
"hộ bố cái",
"cứ gọi đấy",
"gọi tới khuya",
"vứt sim",
"bẻ sim",
"giục sim",
"dụt sim",
"càng chửi là càng gọi",
"ăn cơm hay ăn",
"con kia",
"âm mưu lừa đảo",
"âm mưu trốn nợ",
"ăn của người ta",
"ăn dốc nói láo",
"ăn gì tôi cúng",
"ăn gì tui cúng",
"ăn giựt tiền",
"ăn quỵt tiền",
"anh vẫn còn sống mà",
"bị điếc",
"biến giùm",
"biến dùm",
"biếng nhác",
"biết đọc không",
"biết suy nghĩ không",
"bố đời",
"có miệng nói chuyện không",
"cơm tù",
"cái mặt mày",
"cái mỏ",
"cái nhân cách",
"cái quần",
"cái trò mèo",
"cạp đất ăn",
"cất cái mặt đi",
"bị điên",
"có đi học không",
"phải người không",
"phải con người",
"con cháu mình dạy ai nghe",
"con người hay con gì",
"con nợ",
"con ranh",
"đầu óc có vấn đề",
"đâu phải đứa con nít",
"đầy đủ tay chân",
"dạy lại",
"để đức lại",
"làm xấu mặt",
"dơ bẩn",
"dở hơi",
"dối trá",
"đúng chất lừa đảo",
"đừng có báo đời",
"giả điên",
"già mồm",
"gian xảo",
"giật nợ",
"giựt nợ",
"dựt nợ",
"hạng người như",
"hèn chi không có con",
"hèn hạ",
"hèn quá",
"hiểu tiếng việt",
"hùa nhau dựt",
"hùa nhau giật",
"không có học",
"không có não",
"không có ra gì",
"la lớn lên",
"lấy ráy tai",
"lì quá vậy",
"loại người như",
"lớn cái đầu",
"lừa đảo bên tôi",
"lươn lẹo",
"lì vậy",
"mất dạy",
"mất nết",
"mày bảo",
"học lại",
"mày nói cái gì",
"mẹ dạy sao",
"mở cái mồm",
"mở tai ra",
"nết khó ưa",
"nghiệp mình để lại",
"ngoan cố",
"ngu",
"người bắc kì",
"như rẻ rách",
"như giẻ rách",
"nợ ngập đầu",
"nói chuyện dơ",
"nói tiếng con",
"quả báo nhãn tiền",
"ra ngoài đường mà xin",
"rác rưởi",
"sao dạy con",
"mỏ thúi",
"mỏ thối",
"miệng thúi",
"miệng thối",
"mồm thúi",
"mồm thối",
"sống chui sống nhủi",
"suốt đời chỉ nghèo",
"trốn chui",
"suy nghĩ nông cạn",
"tao nói cho mày nghe",
"tay chân lành lặn",
"té đái",
"thái độ bỡn cợt",
"thất đức",
"thất học",
"thiếu giáo dục",
"thiểu năng",
"thiếu văn minh",
"thông đồng lừa đảo",
"thứ đàn ông",
"tính lừa đảo",
"tính trốn nợ",
"to mồm",
"trơ trẽn",
"tính ăn cướp",
"vô dụng",
"vô học",
"vô văn hóa",
"bớt điêu đi",
"cái bản mặt",
"đẻ ra cái trứng",
"cái tư cách",
"chây lì",
"có ăn có học không",
"con nít vậy",
"dân bắc kì",
"đàn ông con trai",
"đéo đáng mặt",
"hư một thế hệ",
"kệ mày",
"không có ăn học",
"không có văn hóa",
"láo toét",
"mang nghiệp",
"mất khả năng giao tiếp",
"năn nỉ quỳ lạy",
"không có nhân cách",
"nhét vào mồm",
"phải con nít đâu",
"đâu phải con nít",
"quá lì",
"xạo vừa phải thôi",
"thằng nhà quê",
"xin tiền nhà mày",
"lấy cái quần",
"nghèo hèn",
"có ăn học không",
"hôi sữa",
"đội quần",
"banh cái tai ra",
"lỗ tai có bị",
"lỗ tai bị",
"hỗn láo",
"đồ thất học",
"súc vật",
"điếc hả",
"bị câm",
"trâu bò",
"có não không",
"thần kinh hả",
"thần kinh có vấn đề",
"tâm thần",
"tán cho vỡ mồm",
"tán cho vỡ mặt",
"ỉa vào mồm",
"đồ thối tha",
"thứ giẻ rách",
"thứ bá dơ",
"cặn bã xã hội",
"não ngắn",
"não không có nếp nhăn",
"tổ cha chúng bây",
"con người hay con gì vậy",
"nói tiếng con bốn chân",
"loại bốn chân",
"ở dưới đất chui lên hả",
"thằng bắc kì",
"ngu dốt",
"mặt dày",
"thằng đàn bà",
"bất tài vô dụng",
"có lớn mà không có khôn",
"thối nát",
"động cái não lên",
"cái mỏ hỗn",
"đàn ông mặc váy",
"già đầu",
"não úng",
"ngu như heo",
"lì như trâu",
"lì như bò",
"lì lợm",
"là con gì",
"lú lẩn",
"tứ chi",
"suy nghĩ bị dị tật",
"suy nghĩ dị tật",
"nghiệp vô mồm",
"võ mồm",
"cái dân lừa đảo",
"thằng thiểu năng",
"ông già mày",
"ăn gì mà lì",
"mắc dại",
"đang sủa hả",
"chai lì",
"không phát triển được trí não",
"não không phát triển",
"mắc dại quá",
"già cái đầu",
"thằng đàn ông",
"tính đàn bà",
"không ăn học",
"phát ngôn ra dơ",
"ăn cướp của người ta",
"như chó",
"to cái mồm",
"bớt mõm lại",
"gọi cho chị sủa",
"sống chi cho chật đất",
"bố mẹ ông đi lừa đảo",
"láo cá",
"láu cá",
"ngu như gì",
"con hư tại mẹ",
"bám váy mẹ",
"cười vô mặt",
"làm trâu làm bò",
"mày",
"tao",
"mày sủa",
"ngồi đó sủa",
"đứng đó sủa",
"sủa lên",
"sủa gì",
"sủa à",
"sủa tiếp",
"con điên",
"thằng điên",
"mày điên",
"nó điên",
"em điên",
"đồ điên",
"nói điên",
"khùng điên",
"điên khùng",
"điên hả",
"điên à",
"lì",
"con khùng",
"thằng khùng",
"mày khùng",
"nó khùng",
"em khùng",
"bị khùng",
"đồ khùng",
"nói khùng",
"khùng hả",
"khùng à",
"nhục",
"ngoắc cái mồm",
"bê đê",
"đồ hèn",
"già hai thứ tóc",
"ngu như bò",
"thần kinh",
"đầu hai thứ tóc",
"óc trâu",
"mở cái não ra",
"ngu ngục",
"bần",
"bần tiện",
"hèn nhát",
"dai như đĩa",
"bố thí",
"nói tiếng người",
"khỏi ngốc đầu lên",
"khỏi ngóc đầu lên",
"nghèo mạt kiếp",
"hạ lưu",
"cái đạo đức ở đâu",
"ăn bậy chứ đừng nói bậy",
"không biết dạy con",
"như ông nội người ta",
"có mấy đồng bạc lẻ",
"đê tiện",
"mày nói chuyện với ai",
"tính dựt hả",
"cúng ba đời ",
"hèn vừa thôi",
"kém thông minh",
"đồ dân tộc",
"cà chớn",
"đú đỡn",
"đú đởn",
"ẳng lên",
"ngớ ngẩn",
"báo đời",
"ăn hại",
"báo hại",
"sống tệ",
"cô hồn",
"rẻ mạt",
"lương lẹo",
"tội lừa đảo",
"lừa đảo chiếm đoạt tài sản",
"hiểu tiếng người",
"con đàn bà",
"mặc váy",
"lú não",
"lú vậy",
"lú rồi",
"bị lú",
"bất lịch sự",
"thích la làng",
"tổ cha chúng bay",
"lú lẫn",
"tôi xem thường",
"đáng xem thường",
"ngu thế",
"tát cho vỡ mồm",
"tát vỡ mồm",
"tát cho vỡ mặt",
"tát vỡ mặt",
"lắp não",
"gắn não",
"cán banh xác",
"cán banh xát",
"cẩn thận với tao",
"chặt đầu",
"chém chết",
"chém giết",
"chết cả nhà",
"cho sập tiệm",
"coi chừng tao",
"còng đầu",
"cồng đầu",
"cưỡng chế",
"đấm bản mặt mày",
"đập hết",
"đập nát nhà",
"dẹp hết",
"đi chết đi",
"đốt bà",
"đốt nhà",
"đừng có ra đường",
"đứt gân máu",
"hình sự",
"khởi tố truy nã",
"khởi tố truy nả",
"kiện tới cùng",
"liệu hồn",
"lôi cái đầu",
"mày cứ đợi đấy",
"muốn ăn chửi",
"nát tiệm giờ",
"san bằng",
"tao chém",
"tao đá vào cái mặt mày",
"tao gặp mày",
"tội phạm",
"truy lùng",
"truy nã",
"vô tù",
"xuống mồ đi",
"cào nhà",
"chém đi",
"coi chừng bản thân",
"chém hộ",
"tù mọt gông",
"cho bà con chòm xóm",
"đăng hình ảnh",
"đập tiệm",
"cẩn thận đi tù",
"chém chết cha",
"đi tù mọc gong",
"chém chết mẹ",
"đi tù mục xương",
"cẩn thận cái mạng",
"cẩn thận tứ chi",
"trông con cho kĩ vào",
"ra đường cẩn thận",
"ra đường xe cán",
"ra đường sét đánh",
"ra đường coi chừng",
"chặt tay",
"chặt chân",
"đăng lên mạng xã hội",
"dán hình lên cột điện",
"tay nào cầm tiền lấy tay đó",
"tế sống",
"gông cổ",
"chôn sống",
"tông xe",
"lôi cái đầu anh ra",
"lôi đầu ba mẹ anh ra trả",
"đập vô cái mặt anh",
"lôi đầu ra",
"truy nã cả gia đình",
"cắt cổ",
"không đưa tiền thì đập vô mặt",
"truy nã tìm con bà",
"lôi đầu",
"lôi đầu cha đầu mẹ ra",
"nghiệp quật",
"câm cái mồm",
"giết người",
"giết chết",
"giết mày",
"giết nó",
"tao giết",
"bị giết",
"đòi giết",
"nó giết",
"chém người",
"chém lộn",
"chém nó",
"chém tao",
"chém ai",
"bị chém",
"đòi chém",
"đâm chém",
"nó chém",
"dọa chém",
"dán lệnh truy nã",
"bỏ tù",
"phát lệnh truy nã",
"nát máy",
"công an bắt",
"truy sát",
"dở cái nhà",
"quậy banh nhà",
"phát tờ rơi thông tin nợ",
"tôi không tha",
"chôn cái sim",
"cho anh đi tù",
"cho chị đi tù",
"kiện đi tù",
"xách đầu ra trả nợ",
"xé lịch",
"đếm lịch",
"công an bắc",
"đăng phây sờ bút",
"đăng phây sờ búc",
"đăng phay sờ bút",
"đăng phay sờ búc",
"đăng phây bút",
"đăng phây búc",
"đăng phay bút",
"đăng phay búc",
"đăng phết bút",
"đăng phết búc",
"đăng phết sờ bút",
"đăng phết sờ búc",
"Tôi đến trường…làm việc với giáo viên",
"Vành móng ngựa",
"dở nhà",
"cha mày",
"bà nội mày",
"biến mẹ mày",
"bố láo",
"bố mày",
"bú cu",
"cái lồn",
"cái lồn mẹ mày",
"câm mẹ cái mồm",
"cạp lồn",
"chó chết",
"chó đẻ",
"chửi con mẹ mày",
"con cặc",
"con chó",
"con đĩ",
"đem dao ra",
"con gái mẹ",
"con mẹ mày",
"con nít ranh",
"cút cái đĩ mẹ mày",
"đầu buồi",
"đầu đất",
"đéo hiểu",
"đéo muốn nghe",
"đéo rảnh",
"đéo thích",
"đĩ chó",
"đĩ mẹ",
"đỉ mẹ mày",
"đĩ ngựa",
"địt cái con mẹ",
"địt con mẹ",
"địt cụ",
"địt mẹ",
"địt mẹ mày",
"đụ đĩ",
"đụ đỉ",
"đụ má",
"đụ mẹ",
"đụ mẹ mày",
"đụ rảnh háng",
"hãm lờ",
"hãm lồn",
"khốn nạn",
"làm quần què gì",
"lồn mẹ mày",
"lì như chó",
"mả bố mày",
"mả cha mày",
"mặt chó mày",
"mày chửi ai vậy",
"mày hãy nghe",
"mày lừa đảo",
"mày nghe cho kĩ",
"mẹ cái bọn",
"ông nội của anh",
"rảnh háng",
"sống chó",
"thằng cha",
"thằng chó",
"thằng chó đẻ",
"thằng lồn",
"thứ hãm",
"tiên sư bố",
"vãi lồn",
"cái mả mẹ",
"mả cha",
"bố nhà mày",
"con lồn này",
"mã bố nhà mày",
"mả bố nhà mày",
"mày bị câm",
"con đỉ mẹ mày",
"con đỉ mẹ nó",
"cạp lồn ăn",
"đĩ mẹ mày",
"chửi con mẹ mày đó",
"quỷ cái",
"nói tiếng con gì",
"đồ dơ bẩn",
"chơi chó",
"đĩ lồn",
"lồn mẹ",
"thằng đĩ",
"chó cái",
"lồn má",
"đồ khốn",
"đù má",
"đù mẹ",
"đồ chó đẻ",
"con đĩ ngựa",
"lồn má mày",
"thằng khốn nạn",
"thằng khốn",
"mẹ mày",
"thằng cha mày",
"đĩ mẹ nó",
"con mặt lồn",
"đầu bùi",
"quần què",
"thằng cha con gái mẹ",
"con mẹ nó",
"chết mẹ mày giờ",
"cái lồn má",
"đụ quen biết mới cho số",
"địt",
"đụ",
"đéo",
"lồn",
"cứt",
"cức",
"ngu như chó",
]

# Các bucket
# buckets = ["B1 BOM", "B2", "B3", "B4B6", "B7+", "B1-B6", "B13 PROMO", "B2B3"]
buckets = ["PREDUE", "PREDUE_Pilot", "B0 PROMO", "B1 NEW"]

# Tạo JSON array hai chiều
result = []

for bucket in buckets:
    bucket_data = {
        "bucket": bucket,
        "items": data
    }
    result.append(bucket_data)

# Chuyển đổi thành JSON
json_result = json.dumps(result, ensure_ascii=False, indent=2)

# In kết quả
print(json_result)
